#517184　[C#テキスト] 17章演習問題
sanada-being/sanada_TextC pull request #18
Opened 2024-12-06 06:04 UTC by sanada-being

17章ではオブジェクト指向プログラミングを実践し、演習問題の解答を作成しました。

・ポリモーフィズムの基礎を学習しました。
・Thmplate Methodを学習しました。
・Strategyパターンを学習しました。

2024-12-13 01:36 UTC, haraguchi-being reviewed
解答の作成ありがとうございます。
いくつかコメントしたため、確認をお願いします。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/ConvertingFromFullwidthToHalfwidth.cs
クラス名について検討してほしいです。
この名前だと数字以外もコンバートしそうに見えます。
あとはクラス名が長めなので、もう少し短くしてもいいかと思います。
[必要であれば、ローマ字を使用しても可です。](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#:~:text=%E7%84%A1%E7%90%86%E3%81%97%E3%81%A6%E5%85%A8%E9%83%A8%E3%82%92%E8%8B%B1%E8%A8%B3%E3%81%99%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%AF%E3%81%AA%E3%81%8F%E3%80%81%E4%BC%9D%E3%82%8F%E3%82%8A%E3%82%84%E3%81%99%E3%81%95%E3%82%92%E5%84%AA%E5%85%88%E3%81%97%E3%81%A6%E3%83%AD%E3%83%BC%E3%83%9E%E5%AD%97%EF%BC%88%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AB%E3%81%AF%E3%83%98%E3%83%9C%E3%83%B3%E5%BC%8F%EF%BC%89%E3%82%82%E6%8E%A1%E7%94%A8%E3%81%99%E3%82%8B)

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            string wFilePath = args[0];
引数を渡して実行した場合はOKです。
ただ、何も引数が無い場合「ファイルパスを指定してください。」だけ表示されて終了する状態になっています。
ユーザー側の入力を待つ処理を足してみてください。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            }
例外処理Goodです。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                var wTo = GetConverter("変換先の単位を入力してください");
ここは、何を入力すればいいかわからないため、単位の入力例があるとよいです。
あと、間違った値が入力されたときに何かメッセージが表示されると親切かと思います。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
.csのファイルが多数あって平置きの状態なので、フォルダー分けしてもよいかと思います。
Converter用のフォルダを作って、そこにConverterの.csファイルを格納しておくなど。
そうすると、本体のプログラムがどれかわかりやくなります。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static ConverterBase GetConverter(string vMassege) {
スペルミスかと思いますので修正お願いします。
`vMassege` → `vMessage`

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/ConvertingFromFullwidthToHalfwidth17-3.cs
問題17-1-1と同様です。

2024-12-13 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/Program17-1-3.cs
> +            var wFilePath = args[0];
問題17-1-1と同様です。

2024-12-13 02:05 UTC, sanada-being commented on Chapter17/Chapter17-1-1/ConvertingFromFullwidthToHalfwidth.cs
クラス名を`ZenkakuToHankakuNumbers`に変更しました。

2024-12-13 02:10 UTC, sanada-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            string wFilePath = args[0];
引数が何もない場合はユーザーの入力を受け取って処理を進めるように修正しました。

2024-12-13 02:18 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
`ConverterDirectory`を作成し、コンバーター関係のファイルをそちらに移動させました。

2024-12-13 05:28 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                var wTo = GetConverter("変換先の単位を入力してください");
入力の例となる、使用出来る単位名を表示するように修正しました。
また、` ConverterFactory`クラスに単位名のチェックを追加し、無効な単位名の場合にはその旨を出力するように修正しました。

2024-12-13 05:28 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static ConverterBase GetConverter(string vMassege) {
スペルミスを修正しました。

2024-12-13 05:34 UTC, sanada-being commented on Chapter17/Chapter17-1-3/ConvertingFromFullwidthToHalfwidth17-3.cs
クラス名を`ZenkakuToHankakuNumbers17-3`に修正しました。

2024-12-13 05:37 UTC, sanada-being commented on Chapter17/Chapter17-1-3/Program17-1-3.cs
> +            var wFilePath = args[0];
`Program17-1-1`と同様に修正しました。

2024-12-13 11:05 UTC, r-nishiguchi-being requested changes

2024-12-13 11:05 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/KiloMeterConverter.cs
> +        protected override double Ratio { get { return 1000; } }
こんな感じで書けませんかね？
```
protected override double Ratio => 1000;
```

2024-12-13 11:05 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFrom) {
メソッド名はユーザー入力を受けているのでGetよりReadの方がより適していますね。
何か書籍で指定されていたらすみません。

2024-12-13 14:54 UTC, teshima-being reviewed
少しレビューしましたー。
細かい指摘が多くて恐れ入りますが、確認よろしくお願いします。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        }
細かいですが、`vFilename` → `vFileName`ですね。
また、変数名は適切でしょうか。
このメソッドを使っている側をみるとファイルパスが引数として渡されています。
ファイル名とファイルパスのどちらを受け取るメソッドなのか確認をお願いします。

※`Process()`メソッドや`Initialize()`メソッドについても同様です。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +                    string wLine = wSr.ReadLine();
これまた細かいですが、変数名`wSr`よりかは`wReader`や`wStreamReader`とかの方が良い気がします。
スコープが短いため修正必須ではありませんが、わざわざ省略するほどの文字列でもないです。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +                string wFilepath = Console.ReadLine();
`wFilePath`の打ち間違いでしょうか。
`wFilePath`と`wFilepath`は別物になっているので、ユーザーがファイルパスを入力しても正しく実行されません。

※Program17-1-13.csも同様です。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Initialize(string vFilename) { }
引数についての説明を追加しておきましょう。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Terminate() { }
`Execute()`メソッドは`ZenkakuToHankakuNumbers`クラスでオーバーライドされていますが、`Terminate()`メソッドは現在オーバーライドされておらず、処理を行わない空のメソッドになっています。この状態であれば、メソッド自体を削除するか、初期化と終了処理を派生クラスで定義する設計に変更した方が良いでしょう。どちらを選ぶかは、このクラスの将来的な拡張性や設計意図によります。

※`Initialize()`メソッドも同様です。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/ConverterBase.cs
> +        public double FromMeter(double vMeter) {
引数や戻り値についての説明の追加をお願いします。
もしメソッド名などから自明で不要そうならタグごと削除しておきましょう。
また、ラムダ式を使って簡潔に書けるのでよければ検討してみてください。

※`ToMeter()`メソッド含め、同様に修正できる箇所がないか確認してみてください。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                var wUnit = Console.ReadLine();
これまた細かい指摘ですが、`vMessege → vMessage`ですね。 

また、今の実装だと、メッセージは`変換元の単位を入力してください　使用出来る単位:キロメートル　マイル =>`
と表示され、入力時にカーソルは次の行にあたるため、`=>`の意味があまりないように思います。
⇒ を表示するのであれば、下記のように表示されて、かつカーソルが矢印の右にあると分かりやすい気がします。
```
メッセージは`変換元の単位を入力してください　使用出来る単位:キロメートル　マイル 
=>
```

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/KiloMeterConverter.cs
> +            return vName.ToLower() == "kirometer" || vName == this.UnitName;
`kirometer` → `kilometer`ですね。
ちなみに人間なのでミスは誰にでもあります。私もしょっちゅうミスをします。
大切なのは、自身が書いたコードを見返したり、実際に動作をテストしたりすることで、ミスに気付けるタイミングを適切に設けることです。
実際のプロジェクトでも、「実装者テスト → レビュー → 第三者テスト → 品証検査」という流れで実施することで、不具合を埋め込むことがないようにしています。

今回の例で言うと、実際に英語表記で入力してみたときに正しく動作するかテストしていれば気付くことが出来たかと思います。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/DistanceConverter.cs
> +        public ConverterBase To { get; private set; }
`private set;`にしていますが、特にクラス内でもプロパティ値を変更している箇所がないように見えます。
もし不要なのであればセッターを削除しておきましょう。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                wValue = double.TryParse(wLine, out wTemp) ? (double?)wTemp : null;
`wValue`をnull許容型にしている特別な理由はありますか？
24行目で、`TryParse()`がfalseならwValueにnullを代入し、`wValue`がnullの間はループするようになっていますが、「ユーザーの入力値が数値に変換できない場合はループをする」だけであれば、わざわざnull許容型にしなくても良さそうに思えたため聞いてみた次第です。

変数が取りうる状態を増やすということは、それだけその変数を取り扱うときに注意すべき点が増えるということになります。理由があれば問題ないですが、特に理由がないのであれば極力避けたほうが良いように思います。

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wConverter == null);
※追加課題
先日「リーダブルコード」を読んだと思いますが、リーダブルコードに「do - whileループではなくwhileループを使いましょう」というような記述があったような気がします。
せっかくであれば、他にdo - whileループを使用している箇所も含めて、whileループに書き換えられないか検討してみてください。

コードは通常上から下に読んでいくので、do - whileループを使うとコードを2回読むことになってしまいます。
（上から読み進めたあとに条件が出てくるので、もう一度条件を確認したうえで読み直すことになる。）

2024-12-13 14:54 UTC, teshima-being commented on Chapter17/Chapter17-1-3/TextFileProcessor17-3.cs
> +        }
※参考
[コーディング規約](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#:~:text=%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%EF%BC%9A%E6%8E%A5%E9%A0%AD%E8%BE%9E%E3%81%AE%20%22F%22%20%E3%81%A7%E8%87%AA%E8%BA%AB%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%A0%E3%81%A8%E5%88%86%E3%81%8B%E3%82%8B%E3%81%AE%E3%81%A7%20this%20%E3%82%92%E4%BB%98%E3%81%91%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%E3%81%84%E3%81%84%E3%80%82%E4%BB%98%E3%81%91%E3%81%A6%E3%82%82%E3%81%84%E3%81%84%E3%80%82)にあるように、フィールドには`this`を付けなくても良いです。
（接頭辞のFで自身のフィールドだと分かるため）
付けてもよいですが、31行目や34行目では付いておらず、少し統一感に欠けるのでどちらかに揃えるのが良い気がします。

2024-12-17 01:28 UTC, sanada-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/KiloMeterConverter.cs
> +        protected override double Ratio { get { return 1000; } }
ラムダ式を用いた式形式プロパティに修正しました。

2024-12-17 01:32 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFrom) {
`Read`は外部から値やデータを読み込む時に使って、`Get`は値や計算結果を取得する時に使うイメージであっていますかね？
`ReadDistance`に名前を変更しました。

2024-12-17 01:42 UTC, sanada-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        }
今回はどれもファイルパスを引数に取っているので、`vFilename`から`vFilePath`に修正しました。

2024-12-17 01:43 UTC, sanada-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +                    string wLine = wSr.ReadLine();
明確に伝わるよう変数名を`  wStreamReader` に修正しました。

2024-12-17 01:44 UTC, sanada-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +                string wFilepath = Console.ReadLine();
`string wFilepath` から　`wFilePath`に修正しました。

2024-12-17 01:47 UTC, sanada-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Initialize(string vFilename) { }
「処理を行うファイルパス」という説明を追加しました。

2024-12-17 02:15 UTC, sanada-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Terminate() { }
当初テキストを参考にクラスを作成し、今後なにか使うかもしれないなと思いつつ使わずにそのまま残していました。
今回の設計では使わなかったものなので、空のメソッドは削除しようと思います。

2024-12-17 02:34 UTC, sanada-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/ConverterBase.cs
> +        public double FromMeter(double vMeter) {
記入がなかったXMLコメントに説明を追加しました。
また、`ConverterBase`クラスや`KiloMeterConverter`クラス、`MileConverter`クラスにおいてラムダ式を用いた記述に修正しました。

2024-12-17 02:40 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                var wUnit = Console.ReadLine();
```
  Console.WriteLine(vMessage);
  Console.Write(" => ");
```
  
  として以下のように出力されるように修正しました。
 ```
 メッセージは`変換元の単位を入力してください　使用出来る単位:キロメートル　マイル 
=>
```

2024-12-17 02:44 UTC, sanada-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/KiloMeterConverter.cs
> +            return vName.ToLower() == "kirometer" || vName == this.UnitName;
`kirometer`→`kilometer`に修正しました。
たしかに今回は英語で単位名を入力した場合のチェックを行っていませんでした。
実装したすべてのパターンで動作を確認するように気を付けます。

2024-12-17 02:48 UTC, sanada-being commented on Chapter17/Chapter17-1-2/ConverterDirectory/DistanceConverter.cs
> +        public ConverterBase To { get; private set; }
ゲッターのみに修正しました。

2024-12-17 02:56 UTC, sanada-being commented on Chapter17/Chapter17-1-3/TextFileProcessor17-3.cs
> +        }
`this`を付けない形式に統一しました。

2024-12-17 05:42 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wConverter == null);
とりあえず１回処理を行って条件を満たさなければ繰り返すという条件に当てはまってたので使ってみたのですが、たしかにリーダブルコードには`while`文を使うようにという記述がありましたし、読み手とっては条件が先頭にあるほうが親切ですね。
`do-while`文の部分を`while`文に変更しました。

2024-12-17 05:52 UTC, sanada-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                wValue = double.TryParse(wLine, out wTemp) ? (double?)wTemp : null;
`wValue`がnullの間はループするというところからコードを考えていたため、それに合わせて`wValue`もnull参照型に設定していました。
しかしこの場合は`double`型にして`TryParse`の結果が`false`の場合に処理を繰り返すとするだけでよかったですね。
取りうる状態が増えると意識することが増えるという考え方はとても重要ですね。
無駄なものはなるべく取り除くように気を付けます。

2024-12-17 09:34 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFrom) {
はい、だいたいそんなイメージですね。
名前で悩むときは.Netのメソッドの名前を参考にしてみると良いですよ。
プロパティとかに値を設定するときはSet, 値の読み取りや書き込みはRead/Writeなど
https://learn.microsoft.com/ja-jp/dotnet/api/system.console?view=net-8.0

メソッドで実際に計算しているならCalcとかですね。計算済の値を取得するならGetでもわかります。
個人的にはですが、ListやDictionaryから値やオブジェクトを取るときにGetをよく使ったりしますね。

2024-12-18 01:44 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/ConvertingFromFullwidthToHalfwidth.cs
OKです。修正ありがとうございます。

2024-12-18 01:47 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            string wFilePath = args[0];
OKです。修正ありがとうございます。

2024-12-18 01:48 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                var wTo = GetConverter("変換先の単位を入力してください");
OKです。修正ありがとうございます。

2024-12-18 01:49 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
OKです。対応ありがとうございます。

2024-12-18 01:49 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static ConverterBase GetConverter(string vMassege) {
OKです。修正ありがとうございます。

2024-12-18 01:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/ConvertingFromFullwidthToHalfwidth17-3.cs
OKです。修正ありがとうございます。

2024-12-18 01:51 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/Program17-1-3.cs
> +            var wFilePath = args[0];
OKです。修正ありがとうございます。

2024-12-18 04:26 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                wValue = double.TryParse(wLine, out wTemp) ? (double?)wTemp : null;
改善してくださった`ReadDistance()`メソッドについてですが、`Console.ReadLine()`を`while`文の条件式の中に直接記述することで、`wLine`という変数が不要になり、`Console.ReadLine()`の記述箇所も減らすことが出来ます。
```
static double ReadDistanceRenual(ConverterBase vFrom) {
    Console.WriteLine($"変換したい距離を数字で(単位:{vFrom.UnitName})入力してください");
    double wValue;
    while (!double.TryParse(Console.ReadLine(), out wValue)) {
        Console.WriteLine("無効な入力です。再度変換したい距離を入力してください。");
    }
    return wValue;
}
```

2024-12-23 04:12 UTC, merged